# Generated by Django 4.2 on 2023-05-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='usd_clp',
            field=models.FloatField(),
        ),
    ]
