# Generated by Django 4.2 on 2023-05-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_alter_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
